language: python
python:
  - "3.5"

sudo: enabled

install:
  - ./travis-install.sh

script:
  - ./travis-test.sh

deploy:
  - provider: script
    script: ./travis-deploy.sh
    on:
      all_branches: true

notifications:
  email: false
