---
  - name: update apt packages
    sudo: yes
    apt: update_cache=yes cache_valid_time=3600

  - name: install basic apt packages
    sudo: yes
    apt: pkg={{ item }} state=present
    with_items:
      - curl
      - git
      - npm
